---
abstract: 'Listen to a RabbitMQ exchange and emit the messages to Growl.'
author:
  - 'Tomas (t0m) Doran C<< <bobtfish@bobtfish.net> >>.'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-TailRabbit-Growl
no_index:
  directory:
    - inc
    - t
requires:
  App::TailRabbit: 0
  Mac::Growl: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
